<center>

## 2.1. Numpy basics. Ищем пересечение в 2-х массивах.

Это библиотека для всевозможных математических операций, с большим количеством реализованных методов и возможностью реализовывать свою логику эффективно.  <br>
Например векторные и матричные произведения, которые используюся в машинном обучении, а также рассчет различных статистик. 

Импортируем библиотеку [**numpy**](https://docs.scipy.org/doc/numpy-1.15.1/reference/) и сократим ее название для удобства и поддержания общепринятых обозначений. <br>

In [3]:
import numpy as np

Основа [**numpy**](https://docs.scipy.org/doc/numpy-1.15.1/reference/) это вектора (**array**) и матрицы (**matrix**).<br>
Создадим вектор и попробуем возможности библиотеки.

### Вектора

In [20]:
a = np.array([0, 1, 2, 3, 4, 5, 6])

In [21]:
print(type(a))

<class 'numpy.ndarray'>


In [22]:
print(a.shape, type(a.shape))

(7,) <class 'tuple'>


In [23]:
print(a[0], a[1], a[3]) # индексация по элементам

0 1 3


In [24]:
# берем последний элемент в массиве
a[-1] # индексация диапазоном

6

In [25]:
a[3:]

array([3, 4, 5, 6])

In [27]:
a[::-1] # перевернуть вектор

array([6, 5, 4, 3, 2, 1, 0])

In [31]:
a[0] = 1 # операция присвоения
a

array([1, 1, 2, 3, 4, 5, 6])

In [30]:
print(a + 5)

b = np.array([1., 2, 3, 4])
print(b * 5.5)

[ 6  6  7  8  9 10 11]
[ 5.5 11.  16.5 22. ]


### Матрицы 

Матрицы по сути это таблички без границ.

In [32]:
??np.append

In [34]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, type(a))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] <class 'numpy.ndarray'>


In [44]:
a
a[1:2,:]

array([[5, 6, 7, 8]])

In [45]:
print(type(a))

<class 'numpy.ndarray'>


In [50]:
a[::,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [57]:
print('Наша матрица:')
print(a, a.shape)
print('---')
print('Наша распрямленная матрица:')
print(a.flatten(), type(a.flatten()))

Наша матрица:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
---
Наша распрямленная матрица:
[ 1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>


In [62]:
a.nbytes

48

In [63]:
a.shape

(3, 4)

In [64]:
a.shape[0]* a.shape[1]*8

96

In [65]:
row_r1 = a[1, :] # Индексируемся по строкам матрицы. Первый ряд, помните о том что индексация в Python начинается с 0.
row_r1

array([5, 6, 7, 8])

In [67]:
row_r2 = a[:2, :3]
row_r2

array([[1, 2, 3],
       [5, 6, 7]])

In [68]:
row_r2.base

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[1 2 3]
 [5 6 7]] (2, 3)


In [70]:
row_r2

array([[1, 2, 3],
       [5, 6, 7]])

In [71]:
row_r2.base # Посмотреть изначальную матрицу

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
col_r1 = a[:, 1] # Индексируемся по колонкам матрицы.
print(col_r1)
print('---')
print(col_r1.shape)

[ 2  6 10]
---
(3,)


In [74]:
col_r2 = a[:, 1:3]
print(col_r2)
print('---')
print(col_r2.shape)

[[ 2  3]
 [ 6  7]
 [10 11]]
---
(3, 2)


### Операции

In [82]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print("x = ")
print(x)
print("y = ")
print(y)

# Поэлементное сложение
print("x + y =")
print(x + y, type(x+y))
print(np.add(x, y), type(np.add(x, y)))

x = 
[[1. 2.]
 [3. 4.]]
y = 
[[5. 6.]
 [7. 8.]]
x + y =
[[ 6.  8.]
 [10. 12.]] <class 'numpy.ndarray'>
[[ 6.  8.]
 [10. 12.]] <class 'numpy.ndarray'>


In [83]:
# Поэлементное вычитание
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [84]:
import time

print('Поэлементное умножение')
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))
print('---')
print('Поэлементное деление')
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))
print('---')
print('Поэлементное взятие квадратного корня')
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

%time

Поэлементное умножение
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
---
Поэлементное деление
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
---
Поэлементное взятие квадратного корня
[[1.         1.41421356]
 [1.73205081 2.        ]]
Wall time: 0 ns


### Некоторые полезные методы

### Argmax/argmin

In [107]:
x = np.array(list(range(0,11)))
print("X")
print(x)
print(range(0,11), type(range(0,11)))
print(list(range(0,11)), type(list(range(0,11))))
print(x, type(x))

print("Y")
y = np.array(tuple([1,2,3]))
print(tuple([1,2,3]),type(tuple([1,2,3])))
print(y,"\n",type(y))

z = np.array(range(0,5))
print("Z")
print(z, type(z))

'X: {0}; Y: {1}'.format(x, y)

X
[ 0  1  2  3  4  5  6  7  8  9 10]
range(0, 11) <class 'range'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10] <class 'list'>
[ 0  1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>
Y
(1, 2, 3) <class 'tuple'>
[1 2 3] 
 <class 'numpy.ndarray'>
Z
[0 1 2 3 4] <class 'numpy.ndarray'>


'X: [ 0  1  2  3  4  5  6  7  8  9 10]; Y: [1 2 3]'

In [110]:
print(x.argmax())
print(x.argmin())

5
9


In [112]:
x[5] = 99
x[6] = 99
x[9] = -99
x

array([  0,   1,   2,   3,   4,  99,  99,   7,   8, -99,  10])

In [113]:
print(x.argmax()) # Показывает индекс максимального значения, бывает очень полезно при поиске значений в массиве
print(x.argmin()) # Показывает индекс минимального значения

5
9


### Transpose

In [117]:
a = np.array([[1,2,3,4], [5,6,7,8]])
b = np.array([1,2,3,4])
print(a)
print(b)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]


In [121]:
print(a.T) # транспонирование или переворачивание объекта вокруг диагональной оси
print(a[1:2,:])
print(a[1:2,:].T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[5 6 7 8]]
[[5]
 [6]
 [7]
 [8]]


In [123]:
a = np.array([['may','june','july','august'], [100,101,102,500]])
print(a)
print('---')
print(a.T)

[['may' 'june' 'july' 'august']
 ['100' '101' '102' '500']]
---
[['may' '100']
 ['june' '101']
 ['july' '102']
 ['august' '500']]


In [124]:
print(x)
print(x.T)

[  0   1   2   3   4  99  99   7   8 -99  10]
[  0   1   2   3   4  99  99   7   8 -99  10]


### Append

In [131]:
a = np.array(['may', 'june', 'july', 'august'])
a.append('august')

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [126]:
?np.append()

Object `np.append()` not found.


In [132]:
print(np.append(a,'august'))
print(a)
a = np.append(a,'august') # Надо переназначать объект/ присваивать его заново после операций, чтобы он обновился.
print(a)

['may' 'june' 'july' 'august' 'august']
['may' 'june' 'july' 'august']
['may' 'june' 'july' 'august' 'august']


### Unique

In [133]:
np.unique(a)

array(['august', 'july', 'june', 'may'], dtype='<U6')

In [134]:
b = np.unique(a)
b

array(['august', 'july', 'june', 'may'], dtype='<U6')

In [135]:
a

array(['may', 'june', 'july', 'august', 'august'], dtype='<U6')

### Concatenate

In [ ]:
spring = np.array(['march', 'april', 'may'])
summer = np.array(['june', 'july', 'august'])
warm_months = np.concatenate([spring, summer])
warm_months

array(['march', 'april', 'may', 'june', 'july', 'august'], dtype='<U6')

In [136]:
??np.concatenate

### Nonzero

In [138]:
a = np.array([100,101,102,500,0])
print('Наш вектор длиной:')
print(len(a))
print('---')
print('Метод покажет ненулевые индексы:')
print(np.nonzero(a)) 
print('Вывести значения можно так:')
print(a[np.nonzero(a)]) 
print('Проверим длину:')
print(len(a[np.nonzero(a)]))

#print(len(np.argwhere(a)))

Наш вектор длиной:
5
---
Метод покажет ненулевые индексы:
(array([0, 1, 2, 3], dtype=int64),)
Вывести значения можно так:
[100 101 102 500]
Проверим длину:
4


## Пересечение двух массивов

Нередко стоит задача найти общие объекты среди 2-х массивов и найти общие элементы. 

In [139]:
a = np.array([1,10,100,1000])
b = np.array([1,4,100])

А теперь пересечем их методом **np.intersect1d()** и передадим 2 вектора в качестве аргументов.

In [140]:
c = np.intersect1d(a, b)
c

array([  1, 100])

Чтобы не лезть в интеренет и искать документацию, опять же, можно использовать встроенную документацию в Python.

In [ ]:
??np.intersect1d

Этот метод, конечно, работает не только с цифрами, но и с другими объектами, например с строками.

In [141]:
a = np.array(['Юля', 'Олег', 'Роман', 'Иван'])
b = np.array(['Юля','Иван','Леонид'])

In [147]:
c = np.intersect1d(a,b)
c

array(['Иван', 'Юля'], dtype='<U6')

Вспомним метод, который показывает размерности объекта. <br>
И не смотря на то, что у нас всего-лишь вектор, метод **.size** выведет нам количество объектов, которые содержатся в результирующем векторе ( который тоже в свою очередь является объектом, потому что все в Python, как мы помним, это объект!).

In [149]:
c.size

2

Тоже самое мы можем найти, используя метод **len( )**, встроенный в язык Python, который измеряет длину вектора.

In [148]:
len(c)

2

TypeError: 'tuple' object is not callable

Так же часто встает задача найти значения, которые не являются общими, эдакие эксклюзивные значения из 2х векторов/наборов объектов.
Это тоже можно сделать в одну строчку с помощью метода **.setxor1d()** передав ему 2 вектора в качестве аргументов.

In [ ]:
??np.
(a, b)

### Более жизненный пример.

На "игрушечном" ималеньком массиве мы смогли построить пересечение. Принцип остается тот же, если мы ,например, хотим найти пересечение между большим количеством объектов.<br>
Допустим у нас есть какие-либо id пользователей и нам нужно найти пересечение между группами.

Импортируем ниже библиотеку random, с помощью которой можно нагенерить числа, например 4-х значные.<br>
Сделаем списки 

In [153]:
import random
import time

%time
customer_ids_a = random.sample(range(1000000, 50000000), 10000000)
customer_ids_b = random.sample(range(1000000, 50000000), 10000000)

Wall time: 0 ns


Посмотрим на наши массивы, делая срезы в 5 и 10 элементов.

In [154]:
print('Массив А:%s'%customer_ids_a[:5])
print('Массив Б:%s'%customer_ids_b[:10])

Массив А:[271568628, 433447658, 135322621, 3862184, 351550300]
Массив Б:[471690267, 385617797, 239778895, 301345204, 266161691, 426159891, 345494997, 369717587, 240829725, 151213474]


В таких задачах так же могут попадаться неуникальные или повторяющиеся значения, которые не хотелось бы использовать, чтобы избежать ошибок и коллизий.<br>
Вспомним упомянутый выше удобный метод **.unique()**, который возвращает нам только уникальные значения обхекта к которому мы его применям.<br>
Проверим наши вектора на уникальность.

In [ ]:
print('Уникальныых значений в массиве А: %s'% len(np.unique(customer_ids_a)))
print('Уникальныых значений в массиве Б: %s'% len(np.unique(customer_ids_b)))

Уникальныых значений в массиве А: 1000000
Уникальныых значений в массиве Б: 1000000


Все проверив, мы можем применить метод **.intersect1d()** и посмотреть на пересечение.

In [ ]:
%time
c = np.intersect1d(customer_ids_a,customer_ids_b)

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 11.2 µs


In [ ]:
c

array([1000022, 1000024, 1000035, ..., 4999951, 4999973, 4999997])

Так как у нас довольно большое количество элементов в списке, то веротяность того что будет хотя бы одно пересечение довольно высока. 
Посмотрим на то, что у нас получилось.

У нас получился вектор пересечений, который не вмещается строчку отображения в Jupyter notebook, так что давайте посмотрим на то сколько у нас получилось в нем объектов, используя метод **len()**.

In [ ]:
print('Наше пересечение равно %s объектам.' %len(c))

Наше пересечение равно 250572 объектам.


В 1 строчкe можно посчитать отношение нашего пересечения к количеству id нашего массива, в котором мы искали пересечение.

In [ ]:
len(c)/len(customer_ids_b)*100

25.0572

И предстваить его в более читаемом и осмысленном виде.

In [ ]:
print('Наше пересечение равно %s процентов.'%round(len(c)/len(customer_ids_b)*100,2))

Наше пересечение равно 25.06 процентов.


Другие методы для выполнения математических и логических операций с векторами и матрицами можно найти в документации на официальном сайте [библиотеки](https://docs.scipy.org/doc/numpy-1.15.1/reference/).